### ISSUE TITLE
Create postgres databases through mission control - [SEED-483]

### ISSUE THREAD

**Issue by TrevorOctober** [praekelt/mc2#110] opened 2016-09-07 15:30 UTC

**Comment by TrevorOctober** [comment] 2016-09-07 19:05
- [ ] Add fields to base model

- [ ] Show postgres_db_needed in edit view (for both base and docker)

- [ ] Make call to xylem-api when update_marathon is called

- [ ] Save returned values from xylem-api

- [ ] Show postgres fields as read-only in edit view

**Comment by miltontony** [comment] 2016-09-15 19:16
duplicate of #113

**Closed by miltontony** 2016-09-15 19:16 UTC
